# Default image (https://hub.docker.com/_/microsoft-dotnet-core-sdk/)
image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019

#include:
#  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

before_script:
  - dotnet --version

# Build
build_model:
  stage: build
  tags: [windows]
  script:
    - dotnet build Catan.Model

build_view:
  stage: build
  # Windows-based docker images for .NET Framework:
  # https://hub.docker.com/_/microsoft-dotnet-framework-sdk/
  image: mcr.microsoft.com/dotnet/framework/sdk:4.8
  tags: [windows]
  script:
    - dotnet build Catan.sln


# Test
test_model:
  stage: test
  tags: [windows]
  script:
    - dotnet test Catan.Model.Test

#code_quality:
#  before_script:
#  - ''
#  artifacts:
#    paths: [gl-code-quality-report.json]

# Documentation
pages:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:6.0
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq doxygen graphviz
  script:
    - doxygen
    - cp -r doc/html/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - main
